name: get_done
description: A new Flutter Productivity Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  cloud_firestore: ^2.2.2
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  firebase_messaging: ^10.0.2
  firebase_analytics: ^8.1.2
  google_sign_in: ^5.0.4
  hsv_color_pickers: ^0.1.0
  google_fonts: ^2.1.0
  flutter_spinkit: ^5.0.0
  wave: ^0.2.0
  wakelock: ^0.5.2
  flutter_riverpod: ^0.14.0+3
  shared_preferences: ^2.0.6
  text_style_editor: ^1.1.1
  google_mobile_ads: ^0.13.1
  just_audio: ^0.8.0
  args: ^2.1.1
  connectivity: ^3.0.6
  overlay_support: ^1.2.1
  animated_splash_screen: ^1.1.0


  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_local_notifications: ^6.0.0
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.3
#  flutter_launcher_icons: ^0.9.0
#  flutter_native_splash: ^1.2.0

#
#flutter_icons:
#  android: true
#  ios: true
#  remove_alpha_ios: true
#  image_path: "assets/images/ic_launcher.png"
#  adaptive_icon_foreground: "assets/images/ic_launcher.png"
#  adaptive_icon_background: "assets/images/ic_launcher.png"


flutter:

  assets:
    - assets/images/
    - assets/sounds/

  uses-material-design: true
#
#flutter_native_splash:
#  color: "#000000"
#  image: assets/images/ic_launcher.png
#  android: true
#  ios: true
#  fullscreen : true
#  android12 : true
#  android_gravity : center



